name: Functinal suite

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main, functional-workflows ]

jobs:
  func:
    name: Functional tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        series: ["bionic", "focal", "jammy"]
    timeout-minutes: 60
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
      - name: Run tests on ${{ matrix.series }} series
        run: tox -e func -- --series ${{ matrix.series }}

